apiVersion: v1
kind: Service
metadata:
  name: nodeport
  annotations:
    cloud.google.com/backend-config: '{"default": "gogle-backendconfig"}'
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    tier: was
  type: NodePort
